language: node_js
node_js:
  - node
cache: yarn
deploy:
  provider: npm
  email: micha@famreiser.ch
  api_key:
    secure: Q8HzlOKJTk7FLlqIO+ZvwPqGPFZOgSiMJrn+zTP7QkPcvuV64nyBLqgh8T58S4DaKbrFgfBfj0Oge5ezPheGVI5Uy2f+coYyjz2CsYAvO4XPiSIGwqQ8Oiw6VL2UNmHGNxUqegN70OXPmTkyF12uvHNnKKXdSmQmNnqoyXZhD7r1w4WFgZoHTymvKj/TzBAb+lurITt7UrT842pPf3p9xTAQdbV4NLPs9ySSFJsQxEiiApW2JA27YEAKqgc9uDZSEQYyu+ueC5M4fU0RSlk6WlQyJcL8pOrjtkm7j3kRYaD9KtN8mBN6p9fC1w0XlL67KfELqGhWw6yJukhHBOeXxASIH5iWs7OPqtNvjuODc4bYRXmH7bVPJc4sE8HvdjU6NpZJshZV5bT7aORJmXpY6OVKf8016Kjw/YJTzFW0gToNHUbyUT5GvpszQWioA5wfRGLc33hquLdF3BrowLTbUqFn1cWl/W4wbe6N0buy0/RQtf/zjeJFNKltf+TSqYz4X4s/HtHSxGDqUnPhJTUevMuLhEkOHrdBiS1pt3wQp2+6Yak4XUsvLh8DUP4RGWaujcLCk7wC6B8xMmxAb+36QzItf0UJXe+KDWs9tmDQeoQMM1iJ3Gdy/tj5E4k18G9O0zdGIvn8mL0vy5svKeJXVrmKonIu9W9AN/p2XX8mgyo=
  on:
    tags: true
    repo: MichaReiser/llvm-node
